// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// billing.js
export const FETCH_ACCOUNT = 'FETCH_ACCOUNT'
export const FETCH_SUBSCRIPTIONS = 'FETCH_SUBSCRIPTIONS'
export const FETCH_SUBS_VIEW = 'FETCH_SUBS_VIEW'
